export { default as deleteUser } from './deleteUser'
export { default as getAllUsers } from './getAllUsers'
export { default as getSingleUser } from './getSingleUser'
export { default as registerNewUser } from './registerNewUser'
export { default as updateUser } from './updateUser'
